services:
  app:
    build: .
    image: viral-videos
    user: "${UID}:${GID}"
    env_file: .env
    volumes:
      - ./inputs:/app/inputs
      - ./output:/app/output
      - ./assets:/app/assets
      - ./config:/app/config
      - ./temp:/app/temp
    working_dir: /app
